name: 'Jest Coverage Diff'
description: 'A github action to comment jest coverage diff on a PR'
author: 'Anuraag Puri'
inputs:
  accessToken:
    description: 'access token required to comment on a pr'
    default: ${{ github.token }}
  fullCoverageDiff:
    description: 'get the full coverage with diff or only the diff'
    default: false
  autorun:
    description: Run provided command on both current and target branches
    default: true
  runCommand:
    description: 'custom command to get json-summary'
    default: 'npx jest --coverage --coverageReporters="json-summary" --coverageDirectory="./"'
  afterSwitchCommand:
    description: 'command to run after switching to default branch'
    default: null
  delta:
    description: 'Difference between the old and final test coverage'
    default: 100
  total_delta:
    description: 'Difference between the old and final test coverage at the total level'
    default: null
  useSameComment:
    description: 'While commenting on the PR update the existing comment'
    default: false
  postComment:
    description: 'Post comment to the PR'
    default: true
  oldCodeCoveragePath:
    description: 'Path to old code coverage report in json-summary format'
  newCodeCoveragePath:
    description: 'Path to old code coverage report in json-summary format'
outputs:
  report:
    description: Coverage report in markdown format
branding:
  color: red
  icon: git-pull-request
runs:
  using: 'node12'
  main: 'dist/index.js'
